### PR TITLE
Update to v2 api. Migrated from legacy remote control to Companion Server

### PR DESCRIPTION
**Pull request by misalibaytb**
I saw that this plugin was outdated. 
So i want to make pull request to fix these problems and here we are. 
This pull request consists of new authorization method and small refactor in types and error messages, and fixed controlls to work with new v2 api. 
Also i didn't made websocket after 5hours of debbuging get to work, so i made tick function that is runned every 10s to check if there is update. 
And if user updates state inside vs code like pause or play or repeat mode change it will reflect instantly.

### CODE REVIEW

**Review by misalibaytb — COMMENTED** [review]
Also i already created issue if the socket problem is only for this or not and if i find solution i will create another pull request for this to migrate it from periodical fetch to realtime updates from socket

**Comment by sedders123** [comment]
Thank you so much for this! 

Unfortunately when running this I was getting errors to do with authentication and while trying to fix them I came across this rate limit exception.
image

As the API is rate limited I think we want to use the socket and I have thrown together #369 which adds support for V2 using the new socket API. I'm going to run the updated extensions for a day or two and if I don't get any exceptions or issues I'll merge my PR and do a release on the marketplace. If you'd like to help test you can download the extension from the CI artifact (https://github.com/sedders123/vscode-ytmusic/actions/runs/12384129133) and [install the VSIX](https://stackoverflow.com/a/50232194/5179209)

**Review by misalibaytb — COMMENTED** [review]
Yeah i was looking in source code of Companion server and they are strict with rate limiting. if you want you can check [/src/main/integrations/companion-server/api/v1/index.ts](https://github.com/ytmdesktop/ytmdesktop/blob/development/src/main/integrations/companion-server/api/v1/index.ts)

**Review by misalibaytb — COMMENTED** [review]
I will look again into socket thing and try to get it work.

**Comment by misalibaytb** [comment]
Oh i see you got socket to work. I am glad i could help you with this extension

**Comment by sedders123** [comment]
Closing this out as we have merged #369. Although we went in a different direction I want to say thanks again for your support here! I really appreciate your willingness to help out :)

**Comment by misalibaytb** [comment]
> Closing this out as we have merged #369. Although we went in a different direction I want to say thanks again for your support here! I really appreciate your willingness to help out :)

i am happy to help you and no worry i am happy it works and also that the socket works because i couldn't get it to work while i was editing it.

**Pull request closed without merging**
